### ISSUE TITLE
netspeed does not show ppp0 traffic

### ISSUE THREAD

**Issue by denispr** [mgedmin/indicator-netspeed#4] opened 2014-07-12 15:38 UTC
I'm connected to the internet through a speedtouch modem, so the used interface is ppp0.
Unfortunately, that interface is not displayed in netspeed interfaces list. Only eth0 and wlan0.

**Comment by TobBrandt** [comment] 2014-07-12 17:33
Please try the following in a console:

```
killall indicator-netspeed && indicator-netspeed & disown
```

Does your interface now appear in the list?

If not, please post the output of

```
ifconfig
```

**Comment by denispr** [comment] 2014-07-12 18:46
yes, now ppp0 appears on the list.
But selecting it in the list does not work, wlan0 still appears as the monitored interface and downloading files shows "0,0 Kb/s" in netspeed.

**Comment by TobBrandt** [comment] 2014-07-12 19:40
The reason why ppp0 doesn't initially appear in the list is probably that indicator-netspeed starts before the modem is picked up by the OS. We never refresh the interface list after it's populated once (that's a known issue, I'll create a ticket for it).

However, I would have expected ppp0 to be selectable after the restart. Can you select "all"? Does that show any traffic?

**Comment by denispr** [comment] 2014-07-12 19:55
selecting "all" does not work either, "wlan0" still appears as the monitored interface after that operation.

**Comment by TobBrandt** [comment] 2014-07-12 20:36
Could you please select ppp0 from the interface list, then run the following in a console and post the output

```
dconf read /apps/indicators/netspeed/if-name
```

In case you don't have `dconf` installed, you need to install package `dconf-cli` (at least that's how it's called on Debian and Ubuntu).

**Comment by denispr** [comment] 2014-07-12 20:47
well, strangely, after I performed dconf read /apps/indicators/netspeed/if-name (which returned "ppp0"), netspeed works, displaying non zero throughput and showing that the monitored interface is ppp0...

**Comment by TobBrandt** [comment] 2014-07-12 20:49
Interesting. I will investigate this further and get back to you. Thanks for your input!

**Comment by TobBrandt** [comment] 2014-07-12 21:31
I've added some tracing. Would you be so kind and check out to the latest revision, go to the checkout directory, then execute

```
make
killall indicator-netspeed
./indicator-netspeed --trace
```

and after a few second you can kill it with Ctrl+C.

The output should show something like

```
Tracing is on
populating list of interfaces
adding interface eth0
skipping loopback interface
adding interface ppp0
adding interface wlan0
```

followed by repeatedly

```
getting net traffic...
selected interface is ppp0
```

and

```
processing interface XXX
```

for each interface.

What does it do for interface ppp0. Does it show any in/out traffic or does it say "skipping"? Does "processing interface ppp0" appear at all?

**Comment by denispr** [comment] 2014-07-13 05:41
Good news, after rebooting, it still worked, showing traffic on ppp0.

## And after recompiling with the tracing option, the output is:

Tracing is on
populating list of interfaces
adding interface ppp0
adding interface wlan0
skipping loopback interface
adding interface eth0

getting net traffic...
selected interface is ppp0

processing interface ppp0
in: 164595, out: 0

processing interface wlan0
skipping

processing interface lo
skipping loopback interface

processing interface eth0
skipping

## ...

Just one thing, I also tried to select "all", just to see what it does, and it made indicator-netspeed crash with segmentation fault.

**Comment by TobBrandt** [comment] 2014-07-17 17:16
> Just one thing, I also tried to select "all", just to see what it does, and it made indicator-netspeed crash with segmentation fault.

Does that happen every time you click all? I can not reproduce this here.

**Comment by denispr** [comment] 2014-07-17 18:48
I tried three times, it happened each time.

**Comment by TobBrandt** [comment] 2014-07-17 19:45
Sorry, my fault. Recompiling helps :-)

This problem should be fixed now. I introduced it accidentally in my previous commit. In my defense: the GTK docs aren't very clear on who owns what memory and who's responsibility it is to free it again.

**Closed as completed by TobBrandt** 2014-07-17 19:45 UTC

**Comment by denispr** [comment] 2014-07-18 07:01
Thanks, I tested the new release, no more crash !
